from interfaces.habitat.terrestrial import ITerrestrial
from .animal.freshwater import IFreshwater
from .animal.saltwater import ISaltwater
from interfaces.habitat.aquatic import IAquatic
from .animal.flying import IFlying
from .animal.walking import IWalking
from .animal.swimming import ISwimming
from .identifiable import Identifiable
from interfaces.habitat.contains_animals import IContainsAnimals
from interfaces.habitat.contains_plants import IContainsPlants
